package:
  name: esgcet
  version: VERSION

source:
  git_rev: BRANCH
  git_url: https://github.com/muryanto1/esg-publisher.git
  # git_rev: update-gen-five-pkg
  # git_url: https://github.com/muryanto1/esg-publisher.git
  # path: /export/muryanto1/work/publisher/esg-publisher
build:
  number: 1
  noarch: python
  script: cd pkg; python setup.py install

requirements:
  host:
    - python
    - setuptools
    - pip
    - libnetcdf
    - libnetcdf * nompi_*
    - cmor
  run:
    - python
    - pip
    - libnetcdf
    - libnetcdf * nompi_*
    - requests
    - cmor

test:
  commands:
    - python -c "import esgcet"

about:
  home: http://github.com/esgf/esg-publisher
  summary: gen five publisher
  license: BSD
  license_file: bsd-3-clause.txt

