package:
  name: esgcet
  version: 0.1

source:
  git_rev: update-gen-five-pkg
  git_url: https://github.com/muryanto1/esg-publisher.git

build:
  number: 0
  noarch: python
  script: cd pkg; python setup.py install

requirements:
  host:
    - python
    - setuptools
    - pip
    - libnetcdf
    - cmor
  run:
    - python {{ python }}
    - pip
    - libnetcdf
    - cmor

test:
  commands:
    - python -c "import esgcet"

about:
  home: http://github.com/esgf/esg-publisher
  summary: gen five publisher
  license: BSD
  license_file: bsd-3-clause.txt

